### ISSUE TITLE
Full example

### ISSUE THREAD

**Issue by mhekeler** [silvioprog/brookframework#119]
Hello all,

in the demo folder there are really good examples.
But is there an opensourced webapp written with the brookframework, where I can learn best practice on how to create  a whole app?

**Comment by silvioprog** [comment]
Hello @mhekeler 

I did some commercial APIs and sites using Brook framework 3.0, and I'm working a lot to release the version 4.0, because this new release will be focused in performance and productivity.

Unfortunately I can't publish the source code of the APIs, but you can see two public web sites written with Brook here:

1. https://duallsistemas.com.br/site/#/
2. https://duallsistemas.com.br/duallsms/login/

I'm teaching Brook here in Brazil, so I did a web site to publish the course:

1. http://brookframework.org/ead/

And in a quick search in Github, I found some open source applications written in Brook 3.0:

1. https://github.com/leonardorame/cecistore (active development)
2. https://github.com/rbmuc/EasyBBS
3. https://github.com/herux/ypudfootballstatistics
4. https://github.com/seanachaidh/seanblog

However, if you get some dificulty to use Brook, feel free to publish it with us via [Brook community](https://plus.google.com/u/0/communities/101133820055678331036).
