### ISSUE TITLE
Push Notification to client from Server

### ISSUE THREAD

**Issue by shariful2011** [silvioprog/brookframework#121]
Is there any possibilities to Push Notification to client(delphi) from server(lazarus)?

**Comment by silvioprog** [comment]
What is Push Notification?

**Comment by leledumbo** [comment]
> What is Push Notification?

It's a notification protocol commonly found in today's mobile OS, but also exists on many desktop apps. Instead of having the client repeatedly ask the server for new data (polling), the server maintains a connection to the client such that whenever a new data exists in the server it will be sent to the client though that connection and the client can react accordingly without wasting CPU cycles. [Here's the respective wikipedia entry](https://en.wikipedia.org/wiki/Push_technology) which explains a couple of possible way to achieve it.

**Comment by silvioprog** [comment]
Very nice.

**Comment by silvioprog** [comment]
Closing due to long time issue but please feel absolute free to reissue if you want to implement this feature. :+1:
