### ISSUE TITLE
:name not working

### ISSUE THREAD

**Issue by MFernstrom** [silvioprog/brookframework#139]
According to https://brookframework.org/doc/BrookAction.TBrookAction.html#Register I should be able to register urls such as /user/:id, and be able to read that value with Values.Values['id'].

I get Identifier not found "Values", however.

Is this a known bug or OSX-issue?

**Comment by leledumbo** [comment]
Without any code, we can only guess:
* Are you inside TBrookAction's method?
* Do you get the latest framework code?

**Comment by MFernstrom** [comment]
I'm using the latest code, downloaded and rebuilt just now.

I'm inside an action, where I register a path such as TUser.Register('/user/:id');

According to the docs I should be able to do Values.Values['id'], but I get the error.

**Comment by leledumbo** [comment]
OK,  I didn't realize that it has been renamed to Variables instead of Values, the docs need update.

**Comment by MFernstrom** [comment]
Aha, that did the trick.

Thanks again, leledumbo, I owe you at least a keg of beer at this point.

I'll leave this open for now, since there's a discrepancy between the docs and reality.

**Comment by MFernstrom** [comment]
It looks like the docs are still wrong, how do we get them updated?

**Comment by leledumbo** [comment]
> how do we get them updated?

Somebody commit and push the change (well, I practically have the permission to do so...)

**Comment by silvioprog** [comment]
Hi dudes. First, thanks for reporting and using Brook, and sorry for late answers. @leledumbo you I'll be able to push commits/PR etc., because I added you (and @MFernstrom too) as developer of the [Risoflora organization](https://github.com/risoflora). I'm inclined to move Brook framework to this organization! :-) Closing because the documentation I'll be updated in the new release that is coming in next days.
