### ISSUE TITLE
Session between units?

### ISSUE THREAD

**Issue by MFernstrom** [silvioprog/brookframework#140]
This is probably a noob question, but how do I implement sessions so it's accessible from multiple units?

**Comment by leledumbo** [comment]
A brook session works standalone as object, it only depends on `TBrookRequest` on `Start()` and `TBrookRequest` on `Finish()`. You can declare it in a shared unit globally or create a base class having it as a property, then make all actions descend from this base class (of course this base class must extend `TBrookAction` to make it work).

**Comment by MFernstrom** [comment]
Thank you for your patience leledumbo.

Using the demo as the example: https://github.com/silvioprog/brookframework/blob/master/demos/simple/session/test.pas

How could I turn that into a shared unit so that I have a session with the counter accessible from other units?

I think what I'm having the most issue with is figuring out how to deal with the create and destroy to initialize the session.

**Comment by leledumbo** [comment]
Just move `FSession: TSession;` to interface section of the unit instead of `TMyAction`'s field and the `.Create` and `.Free` to initialization and finalization section of the unit, instead of in `TMyAction`'s constructor / destructor. Now you can use FSession from anywhere, just don't forget to `Start` and `Finish` it (a good reason to make a base class that does this).

**Comment by silvioprog** [comment]
@MFernstrom thanks for asking and @leledumbo thanks for answering, I was busy all these days (company, moved to another city, other projects etc.). It seems this issue was solved, so I'm going to close it, but please feel free to reissue if you get other questions.
