### ISSUE TITLE
Why plugins projects on github to brookframework is closing?

### ISSUE THREAD

**Issue by Al-Muhandis** [silvioprog/brookframework#149]
Why plugins projects on github to brookframework is closing? For example, doprf:
"I can not continue working at this project, so I am going to discontinue it and delete its repository. Please do your own copy and feel free to continue it by your own!"
Does this means that the brook framework is closed?

**Comment by silvioprog** [comment]
Hi @Al-Muhandis .

All Brook framework plugins will be moved into its repository, that will be moved to Brook-DEV organization: https://github.com/brook-dev . In short, we may see the following links:

- https://github.com/brook-dev (main organization) ![#1ac537](https://placehold.it/15/1ac537/000000?text=+)
- https://github.com/brook-dev/brookframework (brook3 repository) ![#c5f015](https://placehold.it/15/c5f015/000000?text=+)
- https://github.com/brook-dev/brook4rest (brook for rest repository) ![#1ac537](https://placehold.it/15/1ac537/000000?text=+)
- https://github.com/brook-dev/brook4xc8 (brook for xc8 repository) ![#1ac537](https://placehold.it/15/1ac537/000000?text=+)
- https://github.com/brook-dev/brook4curl (brook for curl repository) ![#c5f015](https://placehold.it/15/c5f015/000000?text=+)

and so on. :-) 

![#1ac537](https://placehold.it/15/1ac537/000000?text=+) = Available.
![#c5f015](https://placehold.it/15/c5f015/000000?text=+) = Under construction.

**Comment by Al-Muhandis** [comment]
Hi! Thanks.
I think I understand. Restructuring and transfer of plug-ins to another repository

**Comment by silvioprog** [comment]
Exactly! :-) We will may have something like "https://github.com/brook-dev/brookframework/plugins" for Brook 3 plugins.

**Comment by silvioprog** [comment]
Done: https://github.com/silvioprog/brookframework/tree/master/plugins . This Brook version compiles only on Free Pascal, it will be released as 4.0.0 and tagged to be available for fix bugs only. After that, the 5.0.0 (code name Tardigrade) version will be released. It compiles on Free Pascal and Delphi (tested on XE families) and doesn't depends on external HTTP servers (Apache, Nginx, fcl-http etc.). After releasing 5.0.0, I have plans to help FPC team in the new RTTI support, because I need it to implement a new feature that will be released in 5.1.
