### ISSUE TITLE
Version 4 ?

### ISSUE THREAD

**Issue by trinione** [silvioprog/brookframework#152]
When would Version 4 be out? It's been stated in the site for over a year and in comments.

**Comment by edwinyzh** [comment]
As far as I know, brook 4 is not entirely written in Pascal - it's a C library with a pascal binding:
https://github.com/risoflora/libbrook

**Comment by Al-Muhandis** [comment]
Sadly, if so. The main way for me to learn how the library works to look at the internal source code

**Comment by silvioprog** [comment]
Hello dudes.

@trinione It is already being tested in beta release at [risoflora/libbrook](https://github.com/risoflora/libbrook/tree/master/bindings/pascal). Currently I'm working in full time to finish it and make it available in package managers like APT(Ubuntu/Debian), Pacman(Arch/MinGW), Nuget(MS), GetIt(Delphi), OPK(Lazarus) and so on, allowing the programmers to install it easily in any supported system (Linux/ARM, Windows etc.). [Another work](https://github.com/risoflora/libbrook/tree/pvs_studio_analysis) in progress is to make libbrook OK in tools like [PVS-Studio](https://www.viva64.com/en/inspections), offering more security for Brook users.

@edwinyzh Thanks for replying, you are right. However, specially the Pascal binding will have many pascal-ish features compilable on Free Pascal and Delphi (e.g: dependency injection, cross-platform service/daemon classes, JSON-ish dataset/object serialization, online program version manager and more).

@Al-Muhandis [Since you use FastCGI](https://github.com/silvioprog/brookframework/issues/147#issuecomment-343493999), the Brook library will become your ally, because you will not depend on external HTTP servers anymore, like Apache, Nginx etc. You just will link a small (about 110 kB) static version into your executable and you will have a builtin stand-alone fast HTTP server event-driven based, full debugging support using FastCGI as reverse proxy, and faster than any other stand-alone HTTP server like Apache, MS `http.sys`, FPC/Delphi thread-ish builtin servers. Free Pascal/Delphi programmers already use the static/shared library concept consuming GNU libraries and system APIs following the POSIX standards.

Good news for Brook 3 users: the brook library will allow to run any project based on Brook3, as CGI or FastCGI. And it will be kept as it is, Free Pascal only, however it will be moved to a branch to get updates following the its evolution.

**Comment by trinione** [comment]
Fantastic update! I shall go to the link and download. Thank you.

**Comment by Al-Muhandis** [comment]
@silvioprog Great! Thank you! <<the Brook library will become your ally, because you will not depend on external HTTP servers anymore, like Apache, Nginx etc>> But can I use sites in PHP and fastcgi applications based on Brook4 on the same server as I use that to with Brook3?

**Comment by silvioprog** [comment]
> But can I use sites in PHP and fastcgi applications based on Brook4 on the same server as I use that to with Brook3?

Since the server just redirects the flow to the proxy, the answer is yes, you can. Notice the reverse proxy allows you to communicate many servers. Maybe I'll post some article explaining that.

I have plan to use [PHP's FastCGI header](https://github.com/php/php-src/blob/master/main/fastcgi.h) instead of original one, because the FastCGI's official site is down and the headers I found (which FPC custfcgi seems based on) contains problems that PHP community already fixed. Another feature I have plan to implement is to allow a threading model to the FastCGI plugin (currently FPC's custcfgi doesn't provide any builtin threading support, this responsibility is left to the server).

But notice [I'm working to release the stable and documented library version](https://github.com/risoflora/libbrook/commits/new_api), so there is many tasks to be done before.

**Comment by trinione** [comment]
Seeing activity. Would the Lazarus install be ready soon?

**Comment by silvioprog** [comment]
@trinione Yes. :smiley: Take a look at this branch: [brook-tardigrade](https://github.com/silvioprog/brookframework/tree/tardigrade). It contains the units already done and their respective examples/docs/tests. Currently only some classes for string/map handling that can be tested. Keep monitoring this branch because it is updated constantly.

**Comment by laytonwang** [comment]
Any updated documents about Brook4 for learning ? Thanks!

**Comment by laytonwang** [comment]
Great jobs!
Any updated documents about Brook4 for learning such as REST ? Thanks!
BTW,I worked on FreeBSD,do I have to compile the package by myself?

**Comment by silvioprog** [comment]
@laytonwang thanks! :+1: :smiley: :+1: 

Currently we have only the [reference of the utility classes](https://duallsistemas.com.br/tmp/bk4/doc/pascal/) and their respective [examples](https://github.com/silvioprog/brookframework/tree/tardigrade/Examples) / [tests](https://github.com/silvioprog/brookframework/tree/tardigrade/Test) (we strong recommend to run all the tests and report any bug if found :sunglasses:). I'm working in the router feature (which REST depends on). Current status of that (in Brook library):

* studying the FFI library - because the new Brook router will be able to map and call any routine from any programming language. (almost done)
* studying hardly PCRE2 library - because we will use regex to register a route. (in progress ...)

It would be nice to make Brook library available in BSD systems. Could you help me in this task as soon as the Brook library is release? I already have a good knowledge about to register a programa/library to be available in package managers like APT(Debian/Ubuntu) and Pacman(Mingw/Arch).

**Comment by laytonwang** [comment]
Thanks . That seems a hard challenge for me because I am just a pascal programmer . I would try to study it and let you know my progress  for BSD's pkg and ports system asap.

**Comment by silvioprog** [comment]
Hi dudes, I have good news! A new broker was added containing the following commentary:

```pascal
...
{ Use this unit ONLY if you have a legacy application in Brook 3/4 and wants to
  run it in Brook Tardigrade. }
...
```
it is available [here](https://github.com/silvioprog/brookframework/blob/master/brokers/Tardigrade/brooktardigradebroker.pas) and a [new example](https://github.com/silvioprog/brookframework/tree/master/demos/tardigrade) was added showing how to use that.

Using this new broker, a legacy application based on old Brook versions can run without any external HTTP server (Apache, Nginx, fcl-http etc.), you just need an external small library that can be downloaded [here](https://github.com/risoflora/libsagui/releases).

The Brook version in trunk compiles only on Free Pascal. It will be released as 4.0.0 and tagged to be available for fix bugs only. After that, the 5.0.0 (code name Tardigrade) version will be released. It compiles on Free Pascal and Delphi (tested on XE families) and doesn't depends on external HTTP servers (Apache, Nginx, fcl-http etc.). After releasing 5.0.0, I have plans to help FPC team in the new RTTI support, because I need it to implement a new feature that will be released in 5.1.

Enjoy that!

**Comment by Al-Muhandis** [comment]
Thanks!

> it is available here and a new example was added showing how to use that.

But the links is not available

**Comment by silvioprog** [comment]
Links updated. Thanks for reporting! :-)
